---
name: CI

env:
  ROLE_NAME: bellackn.hass_control

defaults:
  run:
    working-directory: "bellackn.hass_control"

"on":
  pull_request:
  push:
    branches:
      - main

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:

      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          path: '${{ env.ROLE_NAME }}'

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create ansible.cfg
        run: >
          printf '[defaults]\nroles_path=./tests/requirements/:../\ncollections_paths=./tests/requirements/:../'
          > ansible.cfg

      - name: Install test dependencies
        run: pip3 install yamllint ansible ansible-lint --upgrade

      - name: Run linters
        run: |
          yamllint .
          ansible-lint

      - name: Test syntax
        run: ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  galaxy:
    name: "Ansible Galaxy import"
    needs:
      - lint
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "."
    steps:
      - name: Trigger a new import on Ansible Galaxy
        run: |
          curl -s -X POST "https://galaxy.ansible.com/api/v1/imports/" \
            -H "Authorization: Token ${{ secrets.GALAXY_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"github_user": "bellackn", "github_repo": "ansible-role-hass-control", "github_branch": "main"}'
