---
name: Release

"on":
  release:
    types:
      - published

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a new import on Ansible Galaxy
        run: |
          curl -s -X POST "https://galaxy.ansible.com/api/v1/imports/" \
            -H "Authorization: Token ${{ secrets.GALAXY_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"github_user": "bellackn", "github_repo": "ansible-role-hass-control", "github_branch": "main"}'
